### ISSUE TITLE
bioconductor code

### ISSUE THREAD

**Issue by dougwyu** [thackmann/Distanced#1]
suggest adding this to demo.R

```
if (!requireNamespace(c("BiocManager", "devtools"), quietly = FALSE)) install.packages(c("BiocManager", "devtools"))
BiocManager::install(c("ShortRead", "Biostrings", "msa"))
```

**Comment by thackmann** [comment]
Good catch, dougwyu.  As your comment points out, Distanced will not install correctly unless ShortRead, Biostrings, and msa packages are also installed.  One way to solve it is modifying demo.R as you suggested.  I will also see if I can solve it by modifying Distanced.R.   

As I work on the solution, if there are other problems or features you would like to see, please let me know.

**Comment by thackmann** [comment]
I tested a solution, and it works on my laptop that didn't have ShortRead, Biostrings, or msa packages installed. 

The solution was to add
biocViews:
to the DESCRIPTION file. This tells R to install ShortRead, Biostrings, and msa packages when you install the Distanced package.  Specifically, it tells R to look in the Bioconductory repository for the packages.  

You should now be able to install Distanced by using
devtools::install_github(repo="thackmann/distanced", subdir="Distanced")

If prompted during installation, choose "No" to the question "Do you want to install from sources the package which needs compilation?".  Otherwise, installation will fail.  

If this didn't work for you, let me know and I'll troubleshoot some more.

The solution is documented here:
r-lib/devtools#700
